# _config.yml
title: Gabe's Blog
description: Coding and Yapping
baseurl: ""
url: "https://gabehubner.netlify.app"

collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown # Ensure Markdown is supported
highlighter: rouge # Code highlighting
permalink: pretty # Pretty URLs without file extensions
plugins:
  - jekyll-redirect-from

include:
  - "_pages"
  - "admin"

netlify_cms:
  path: admin
  preview_styles: true
