title: Gabe's Blog
description: Coding and Yapping
baseurl: ""
url: "https://gabehubner.netlify.app"

collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown # Ensure Markdown is supported
highlighter: rouge # Code highlighting
permalink: pretty # Pretty URLs without file extensions

plugins:
  - jekyll-redirect-from

netlify_cms:
  # Path to CMS config file
  config_path: "/admin/config.yml"

# Asset configuration for images
assets:
  media_folder: "assets/images" # Folder for media uploads
  public_folder: "/assets/images" # Public URL for media

# Disable Netlify Identity and configure GitHub as OAuth provider
identity:
  enabled: false # Disable Netlify Identity
  provider: github # Use GitHub for authentication

admin:
  path: /admin # Path to the Netlify CMS admin panel
