backend:
  name: github
  repo: ghubnerr/ghubnerr.github.io # GitHub repository for storing content
  branch: blog # Branch for storing CMS-managed content
  base_url: https://api.netlify.com # Required for GitHub authentication via Netlify
  auth_endpoint: /auth/github # Adjusted GitHub auth callback

media_folder: "assets/images" # Folder in the repo for uploaded media files
public_folder: "/assets/images" # Folder on the site for public media access

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts" # Folder where blog posts are stored
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Slug format for blog posts
    editor:
      preview: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "_projects" # Folder where projects are stored
    create: true
    slug: "{{slug}}" # Slug format for projects
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "project",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Technologies", name: "tech", widget: "list" }
      - { label: "GitHub Link", name: "github_link", widget: "string" }
      - {
          label: "Demo Link",
          name: "demo_link",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

# Optional admin settings for Netlify CMS
admin:
  auth:
    github: "ghubnerr" # Restrict access to this GitHub user
